// TRAINING TABLE TYPES
export enum TableType {
  TABLE_TYPE_O2 = 'TABLE_TYPE_O2',
  TABLE_TYPE_CO2 = 'TABLE_TYPE_CO2',
  TABLE_TYPE_FREE = 'TABLE_TYPE_FREE',
  TABLE_TYPE_ENDURANCE = 'TABLE_TYPE_ENDURANCE'
}

// TRAINING SET TYPE
export enum SetType {
  SET_TYPE_PREPARE = 'SET_TYPE_PREPARE',
  SET_TYPE_HOLD = 'SET_TYPE_HOLD'
}

// TRAINING SET MODE
export enum SetMode {
  SET_MODE_INITIAL = 'SET_MODE_INITIAL',
  SET_MODE_RUNNING = 'SET_MODE_RUNNING',
  SET_MODE_FINISHED = 'SET_MODE_FINISHED',
  SET_MODE_SKIPED = 'SET_MODE_SKIPED'
}

export enum CronoMode {
  CRONO_MODE_INITIAL = 'CRONO_MODE_INITIAL',
  CRONO_MODE_AUTO = 'CRONO_MODE_AUTO',
  CRONO_MODE_COACH = 'CRONO_MODE_COACH',
  CRONO_MODE_FINISHED = 'CRONO_MODE_FINISHED'
}
