// TABLE TYPES
export const TABLE_TYPE_O2 = 'TABLE_TYPE_O2'
export const TABLE_TYPE_CO2 = 'TABLE_TYPE_CO2'
export const TABLE_TYPE_FREE = 'TABLE_TYPE_FREE'

// SET TYPE
export const SET_TYPE_PREPARE = 'SET_TYPE_PREPARE'
export const SET_TYPE_HOLD = 'SET_TYPE_HOLD'

// SET MODE
export const SET_MODE_INITIAL = 'SET_MODE_INITIAL'
export const SET_MODE_RUNNING = 'SET_MODE_RUNNING'
export const SET_MODE_FINISHED = 'SET_MODE_FINISHED'
export const SET_MODE_SKIPED = 'SET_MODE_SKIPED'
