const reduxActions = {

    // EDITOR
    EDITOR_BASE_CHANGE: 'EDITOR_BASE_CHANGE',
    EDITOR_TYPE_CHANGE: 'EDITOR_TYPE_CHANGE',
    EDITOR_SET_DURATION_CHANGE: 'EDITOR_SET_DURATION_CHANGE',

    // CRONO
    CRONO_START: 'CRONO_START',
    CRONO_SET_MODE: 'CRONO_SET_MODE',
    CRONO_FINISH: 'CRONO_FINISH',
    CRONO_SET_SKIP: 'CRONO_SET_SKIP',
    CRONO_TICK_UP: 'CRONO_TICK_UP',
};

export default reduxActions;
