// EDITOR
export const EDITOR_SET_INITIAL_STATE = 'EDITOR_SET_INITIAL_STATE';
export const EDITOR_SET_TABLE_BASE = 'EDITOR_SET_TABLE_BASE';
export const EDITOR_SET_TABLE_BASE_BREAKS = 'EDITOR_SET_TABLE_BASE_BREAKS';
export const EDITOR_SET_TABLE_TYPE = 'EDITOR_SET_TABLE_TYPE';
export const EDITOR_SET_TABLE_DURATION = 'EDITOR_SET_TABLE_DURATION';
export const EDITOR_REPLACE_SETS = 'EDITOR_REPLACE_SETS';

// CRONO
export const CRONO_SET_INITIAL_STATE = 'CRONO_SET_INITIAL_STATE';
export const CRONO_SET_START_TIMESTAMP = 'CRONO_SET_START_TIMESTAMP';
export const CRONO_SET_RUNNING_MODE = 'CRONO_SET_RUNNING_MODE';
export const CRONO_SET_RUNNING_TABLE_DURATION = 'CRONO_SET_RUNNING_TABLE_DURATION';
export const CRONO_SET_RUNNING_CONTRACTIONS = 'CRONO_SET_RUNNING_CONTRACTIONS';
export const CRONO_REPLACE_SET = 'CRONO_REPLACE_SET';
export const CRONO_REPLACE_SETS = 'CRONO_REPLACE_SETS';
