// EDITOR
export const EDITOR_SET_INITIAL_STATE: string = 'EDITOR_SET_INITIAL_STATE';
export const EDITOR_SET_TABLE_BASE: string = 'EDITOR_SET_TABLE_BASE';
export const EDITOR_SET_TABLE_BASE_BREAKS: string = 'EDITOR_SET_TABLE_BASE_BREAKS';
export const EDITOR_SET_TABLE_TYPE: string = 'EDITOR_SET_TABLE_TYPE';
export const EDITOR_SET_TABLE_DURATION: string = 'EDITOR_SET_TABLE_DURATION';
export const EDITOR_REPLACE_SETS: string = 'EDITOR_REPLACE_SETS';

// CRONO
export const CRONO_SET_INITIAL_STATE: string = 'CRONO_SET_INITIAL_STATE';
export const CRONO_SET_START_TIMESTAMP: string = 'CRONO_SET_START_TIMESTAMP';
export const CRONO_SET_RUNNING_MODE: string = 'CRONO_SET_RUNNING_MODE';
export const CRONO_SET_RUNNING_TABLE_DURATION: string = 'CRONO_SET_RUNNING_TABLE_DURATION';
export const CRONO_SET_RUNNING_CONTRACTIONS: string = 'CRONO_SET_RUNNING_CONTRACTIONS';
export const CRONO_REPLACE_SET: string = 'CRONO_REPLACE_SET';
export const CRONO_REPLACE_SETS: string = 'CRONO_REPLACE_SETS';