const reduxActions = {

    // EDITOR
    EDITOR_SET_INITIAL_STATE: 'EDITOR_SET_INITIAL_STATE',
    EDITOR_SET_TABLE_BASE: 'EDITOR_SET_TABLE_BASE',
    EDITOR_SET_TABLE_TYPE: 'EDITOR_SET_TABLE_TYPE',
    EDITOR_SET_TABLE_DURATION: 'EDITOR_SET_TABLE_DURATION',
    EDITOR_REPLACE_SETS: 'EDITOR_REPLACE_SETS',

    // CRONO
    CRONO_START: 'CRONO_START',
    CRONO_SET_MODE: 'CRONO_SET_MODE',
    CRONO_FINISH: 'CRONO_FINISH',
    CRONO_SET_SKIP: 'CRONO_SET_SKIP',
    CRONO_TICK_UP: 'CRONO_TICK_UP',

};

export default reduxActions;
