export default reduxActions = {

    // EDITOR
    EDITOR_CHANGE_BASE: 'EDITOR_CHANGE_BASE',
    EDITOR_CHANGE_TYPE: 'EDITOR_CHANGE_TYPE',
    EDITOR_CHANGE_TIME_ITEM: 'EDITOR_CHANGE_TIME_ITEM',

    // CRONO
    CRONO_TIMER_INIT: 'CRONO_TIMER_INIT',
    CRONO_TIMER_STOP: 'CRONO_TIMER_STOP',
    CRONO_TIMER_TICK: 'CRONO_TIMER_TICK',
    CRONO_TIMER_FINISHED: 'CRONO_TIMER_FINISHED',

}
