
const routesEnum = {
    ROOT: 'ROOT',
    MAIN_SCENE: 'MAIN_SCENE',
    CREATE_TABLE_SCENE: 'CREATE_TABLE_SCENE',
    CRONO_SCENE: 'CRONO_SCENE',
    MY_TABLES_SCENE: 'MY_TABLES_SCENE',
    HISTORY_SCENE: 'HISTORY_SCENE',
    ENDURANCE_TABLE_SCENE: 'ENDURANCE_TABLE_SCENE',
    SCHEDULE_SCENE: 'SCHEDULE_SCENE'
};

export { routesEnum };
